// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: proto/models/review.proto

package stubs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Review struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FeedBack []*FeedBackByUser `protobuf:"bytes,1,rep,name=feedBack,proto3" json:"feedBack,omitempty"`
}

func (x *Review) Reset() {
	*x = Review{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_models_review_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_review_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_proto_models_review_proto_rawDescGZIP(), []int{0}
}

func (x *Review) GetFeedBack() []*FeedBackByUser {
	if x != nil {
		return x.FeedBack
	}
	return nil
}

type FeedBackByUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rating   string `protobuf:"bytes,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Comments string `protobuf:"bytes,3,opt,name=comments,proto3" json:"comments,omitempty"`
}

func (x *FeedBackByUser) Reset() {
	*x = FeedBackByUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_models_review_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedBackByUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedBackByUser) ProtoMessage() {}

func (x *FeedBackByUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_models_review_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedBackByUser.ProtoReflect.Descriptor instead.
func (*FeedBackByUser) Descriptor() ([]byte, []int) {
	return file_proto_models_review_proto_rawDescGZIP(), []int{1}
}

func (x *FeedBackByUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FeedBackByUser) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

func (x *FeedBackByUser) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

var File_proto_models_review_proto protoreflect.FileDescriptor

var file_proto_models_review_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x72,
	0x65, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x22, 0x3c, 0x0a, 0x06, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x12, 0x32, 0x0a,
	0x08, 0x66, 0x65, 0x65, 0x64, 0x42, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x42, 0x61, 0x63,
	0x6b, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x08, 0x66, 0x65, 0x65, 0x64, 0x42, 0x61, 0x63,
	0x6b, 0x22, 0x54, 0x0a, 0x0e, 0x46, 0x65, 0x65, 0x64, 0x42, 0x61, 0x63, 0x6b, 0x42, 0x79, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x73, 0x74, 0x75,
	0x62, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_models_review_proto_rawDescOnce sync.Once
	file_proto_models_review_proto_rawDescData = file_proto_models_review_proto_rawDesc
)

func file_proto_models_review_proto_rawDescGZIP() []byte {
	file_proto_models_review_proto_rawDescOnce.Do(func() {
		file_proto_models_review_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_models_review_proto_rawDescData)
	})
	return file_proto_models_review_proto_rawDescData
}

var file_proto_models_review_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_models_review_proto_goTypes = []interface{}{
	(*Review)(nil),         // 0: models.Review
	(*FeedBackByUser)(nil), // 1: models.FeedBackByUser
}
var file_proto_models_review_proto_depIdxs = []int32{
	1, // 0: models.Review.feedBack:type_name -> models.FeedBackByUser
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_models_review_proto_init() }
func file_proto_models_review_proto_init() {
	if File_proto_models_review_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_models_review_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Review); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_models_review_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedBackByUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_models_review_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_models_review_proto_goTypes,
		DependencyIndexes: file_proto_models_review_proto_depIdxs,
		MessageInfos:      file_proto_models_review_proto_msgTypes,
	}.Build()
	File_proto_models_review_proto = out.File
	file_proto_models_review_proto_rawDesc = nil
	file_proto_models_review_proto_goTypes = nil
	file_proto_models_review_proto_depIdxs = nil
}
